name: Build

on:
  push:
    branches:
      - '**'  # Run on all branch pushes
  pull_request:
    branches:
      - '**'  # Run on all pull requests

env:
  GO_VERSION: '1.24'
  APP_NAME: 'touch-block'

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true  # Stop all builds if one fails
      matrix:
        include:
          - os: linux
            arch: amd64
            output-name: linux-x64
          - os: linux
            arch: '386'
            output-name: linux-x86
          - os: linux
            arch: arm64
            output-name: linux-arm64
          - os: linux
            arch: arm
            arm-version: '7'  # ARMv7 for 32-bit ARM
            output-name: linux-arm32

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.arm-version }}
        run: |
          # Build the binary with optimizations
          go build -v -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
            -o ${{ env.APP_NAME }}-${{ matrix.output-name }} .
          
          # Make it executable
          chmod +x ${{ env.APP_NAME }}-${{ matrix.output-name }}
          
          # Show file info for verification
          ls -lh ${{ env.APP_NAME }}-${{ matrix.output-name }}
          file ${{ env.APP_NAME }}-${{ matrix.output-name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.output-name }}
          path: ${{ env.APP_NAME }}-${{ matrix.output-name }}
          retention-days: 90